version: "3.9"

services:
  api-server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    volumes:
      - /full-stack-app/server/node_modules
      - ./server:/full-stack-app/server
    environment:
      - MONGO_URI=
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    volumes:
      - /full-stack-app/client/node_modules
      - ./client:/full-stack-app/client
    stdin_open: true # FIXME: https://github.com/facebook/create-react-app/issues/8688
    ports:
      - "3000:3000"
    depends_on:
      - api-server

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
